-- ============================================================
-- ShareHub · 权限码目录补 3 条（预约调价）
--
-- 【为什么要新迁移而不是改 V72】
-- V72 别人的库已经跑过，改了 Flyway 会因校验和不符拒绝启动。
--
-- 【这 3 条从哪来】
-- 预约调价的端点本次改挂真源表声明的码（功能权限清单 §5：
-- pricing:adjustment:read / :create / :cancel），此前挂的是 pricing:rule:read / :config。
-- 新码一旦被 @perm.can 强制，就必须能在角色勾选树上选得到 ——
-- 否则「端点按它拒人，而管理员在界面上根本授不出去」，且没有任何症状
-- （这正是 PermCatalogCoverageTest 立起来要拦的那件事）。
--
-- 【pricing:rule:config 没有删】
-- 它不再被任何端点强制（perm-catalog-names.tsv 里标志位已改 0），
-- 但目录行保留：iam_role_perm 按 code 关联，删掉会让已经授出去的勾选项凭空消失。
-- 目录里多一条未强制的码无害 —— 它只是选得到而已。
--
-- 本段由 backend/scripts/gen-perm-catalog.py 生成，ON DUPLICATE KEY UPDATE 可重复执行。
-- ============================================================
SET NAMES utf8mb4;

-- 本段由 backend/scripts/gen-perm-catalog.py 生成，请勿手改。
-- 共 179 条（后端强制 161 · 仅目录 18）。
INSERT INTO iam_permission (code, name, module) VALUES
  ('*', '全部权限（超管）', '*'),
  ('agent:*', '代理商 全部', 'agent'),
  ('agent:account:manage', '代理账号 开通/停用', 'agent'),
  ('agent:agent:read', '代理商 查看', 'agent'),
  ('agent:agent:update', '代理商 编辑', 'agent'),
  ('agent:apply:approve', '代理入驻申请 审核', 'agent'),
  ('agent:apply:create', '代理入驻申请 代录', 'agent'),
  ('agent:apply:read', '代理入驻申请 查看', 'agent'),
  ('agent:performance:read', '代理绩效 查看', 'agent'),
  ('agent:scope:assign', '设备/点位 划拨给代理', 'agent'),
  ('agent:settlement:read', '代理结算/收益 查看', 'agent'),
  ('agent:share:config', '代理分润 配置', 'agent'),
  ('cs:*', '客服 全部', 'cs'),
  ('cs:session:read', '客服会话 查看', 'cs'),
  ('cs:session:reply', '客服会话 回复', 'cs'),
  ('cs:ticket:handle', '报障工单 受理', 'cs'),
  ('cs:ticket:read', '报障工单 查看', 'cs'),
  ('cs:ticket:update', '报障工单 编辑', 'cs'),
  ('dashboard:overview:read', '经营总览 查看', 'dashboard'),
  ('dashboard:todo:read', '待办聚合 查看', 'dashboard'),
  ('device:cabinet:*', '机柜 全部', 'device'),
  ('device:cabinet:create', '机柜 新增', 'device'),
  ('device:cabinet:read', '机柜台账 查看', 'device'),
  ('device:cabinet:update', '机柜 编辑', 'device'),
  ('device:command:*', '远程指令 全部', 'device'),
  ('device:command:send', '远程指令 下发', 'device'),
  ('device:inventory:*', '库存调拨 全部', 'device'),
  ('device:inventory:read', '库存/调拨/盘点 查看', 'device'),
  ('device:inventory:transfer', '调拨 执行', 'device'),
  ('device:ota:*', '固件 全部', 'device'),
  ('device:ota:manage', '固件投放 建/改', 'device'),
  ('device:ota:read', '固件版本库 查看', 'device'),
  ('device:powerbank:*', '充电宝 全部', 'device'),
  ('device:powerbank:read', '充电宝 查看', 'device'),
  ('device:powerbank:update', '充电宝 报废/标记', 'device'),
  ('device:slot:read', '仓位 查看', 'device'),
  ('device:vendor:config', '供应商接入 配置', 'device'),
  ('device:vendor:read', '供应商接入 查看', 'device'),
  ('finance:*', '财务 全部', 'finance'),
  ('finance:invoice:issue', '发票 登记/开具', 'finance'),
  ('finance:invoice:read', '发票 查看', 'finance'),
  ('finance:invoice:update', '发票 编辑', 'finance'),
  ('finance:invoice:void', '发票 作废', 'finance'),
  ('finance:ledger:create', '账务分录 记账', 'finance'),
  ('finance:ledger:read', '账务分录 查看', 'finance'),
  ('finance:payout_account:read', '收款账户 查看', 'finance'),
  ('finance:payout_account:update', '收款账户 维护', 'finance'),
  ('finance:recon:handle', '对账差错 处理', 'finance'),
  ('finance:recon:read', '对账 查看', 'finance'),
  ('finance:reconcile:read', '对账 查看', 'finance'),
  ('finance:settlement:confirm', '结算单 确认', 'finance'),
  ('finance:settlement:generate', '结算单 生成', 'finance'),
  ('finance:settlement:read', '结算单 查看', 'finance'),
  ('finance:share_record:read', '分润明细 查看', 'finance'),
  ('finance:share_rule:create', '分润规则 新增', 'finance'),
  ('finance:share_rule:read', '分润规则 查看', 'finance'),
  ('finance:withdrawal:apply', '提现 申请（代理自助）', 'finance'),
  ('finance:withdrawal:audit', '提现 审核', 'finance'),
  ('finance:withdrawal:pay', '提现 打款', 'finance'),
  ('finance:withdrawal:read', '提现 查看', 'finance'),
  ('location:*', '场地 全部', 'location'),
  ('location:analysis:read', '坪效分析 查看', 'location'),
  ('location:contract:create', '合同 新增', 'location'),
  ('location:contract:read', '合同 查看', 'location'),
  ('location:contract:update', '合同 编辑', 'location'),
  ('location:crm:read', 'BD CRM 查看', 'location'),
  ('location:crm:update', 'BD CRM 跟进', 'location'),
  ('location:lead:read', 'BD 线索 查看', 'location'),
  ('location:lead:update', 'BD 线索 编辑', 'location'),
  ('location:overview:read', '站点概览 查看', 'location'),
  ('location:poi:create', '点位 新增', 'location'),
  ('location:poi:read', '点位 查看', 'location'),
  ('location:poi:update', '点位 编辑', 'location'),
  ('location:site:update', '站点 编辑', 'location'),
  ('location:venue:create', '场地方 新增', 'location'),
  ('location:venue:read', '场地方 查看', 'location'),
  ('location:venue:update', '场地方 编辑', 'location'),
  ('marketing:*', '营销 全部', 'marketing'),
  ('marketing:ad:read', '广告位/投放 查看', 'marketing'),
  ('marketing:ad:update', '广告位/投放 维护', 'marketing'),
  ('marketing:campaign:read', '活动 查看', 'marketing'),
  ('marketing:campaign:update', '活动 编辑', 'marketing'),
  ('marketing:coupon:create', '优惠券 新增', 'marketing'),
  ('marketing:coupon:issue', '优惠券 发放', 'marketing'),
  ('marketing:coupon:read', '优惠券 查看', 'marketing'),
  ('marketing:coupon:update', '优惠券 编辑', 'marketing'),
  ('marketing:notice:read', '公告 查看', 'marketing'),
  ('marketing:notice:update', '公告 维护', 'marketing'),
  ('marketing:push:send', '推送触达 发送', 'marketing'),
  ('marketing:push:update', '推送任务 维护', 'marketing'),
  ('marketing:recharge:update', '充值活动 维护', 'marketing'),
  ('marketing:referral:read', '邀请裂变 查看', 'marketing'),
  ('marketing:referral:update', '邀请裂变 维护', 'marketing'),
  ('order:deposit:update', '押金/欠费 处置', 'order'),
  ('order:exception:handle', '异常订单 处置', 'order'),
  ('order:exception:read', '异常订单 查看', 'order'),
  ('order:intervene:execute', '订单干预 执行', 'order'),
  ('order:order:export', '订单 导出', 'order'),
  ('order:order:read', '订单 查看/详情', 'order'),
  ('order:order:update', '订单 编辑', 'order'),
  ('order:refund:apply', '退款 申请', 'order'),
  ('order:refund:audit', '退款 审批', 'order'),
  ('org:audit:read', '操作审计 查看', 'org'),
  ('org:dept:create', '部门 新增', 'org'),
  ('org:dept:read', '组织架构 查看', 'org'),
  ('org:employee:create', '员工 新增', 'org'),
  ('org:employee:read', '员工 查看', 'org'),
  ('org:employee:update', '员工 编辑', 'org'),
  ('org:performance:read', '绩效报表 查看', 'org'),
  ('org:role:read', '角色 查看', 'org'),
  ('org:role:update', '角色 增改删/授权', 'org'),
  ('pricing:*', '计费 全部', 'pricing'),
  ('pricing:adjustment:cancel', '预约调价 撤销', 'pricing'),
  ('pricing:adjustment:create', '预约调价 新建编辑', 'pricing'),
  ('pricing:adjustment:read', '预约调价 查看', 'pricing'),
  ('pricing:plan:create', '计费模板 新增', 'pricing'),
  ('pricing:plan:read', '计费模板 查看', 'pricing'),
  ('pricing:plan:update', '计费模板 编辑', 'pricing'),
  ('pricing:rule:config', '调价单 配置', 'pricing'),
  ('pricing:rule:read', '时段倍率 查看', 'pricing'),
  ('pricing:rule:update', '时段倍率 编辑', 'pricing'),
  ('report:*', '报表 全部', 'report'),
  ('report:consumer:read', '消费者分析 查看', 'report'),
  ('report:custom:read', '自定义报表 查看', 'report'),
  ('report:device:read', '设备报表 查看', 'report'),
  ('report:finance:read', '财务报表 查看', 'report'),
  ('report:location:read', '点位报表 查看', 'report'),
  ('report:screen:read', '实时大屏 查看', 'report'),
  ('system:app_version:read', '应用版本 查看', 'system'),
  ('system:app_version:release', '应用版本 发布', 'system'),
  ('system:bank:read', '银行字典 查看', 'system'),
  ('system:bank:update', '银行字典 编辑', 'system'),
  ('system:biz_rule:read', '业务规则 查看', 'system'),
  ('system:biz_rule:update', '业务规则 编辑', 'system'),
  ('system:brand:read', '品牌 查看', 'system'),
  ('system:brand:update', '品牌 维护', 'system'),
  ('system:dict:read', '参数字典/地区库 查看', 'system'),
  ('system:dict:update', '参数字典/地区库 编辑', 'system'),
  ('system:login_setting:read', '登录设置 查看', 'system'),
  ('system:login_setting:update', '登录设置 编辑', 'system'),
  ('system:market:read', '多国家市场 查看', 'system'),
  ('system:market:update', '多国家市场 编辑', 'system'),
  ('system:notify_blacklist:read', '触达拉黑 查看', 'system'),
  ('system:notify_blacklist:update', '触达拉黑 处置', 'system'),
  ('system:notify_log:read', '发送记录 查看', 'system'),
  ('system:notify_log:update', '发送记录 重发', 'system'),
  ('system:notify_template:read', '通知模板 查看', 'system'),
  ('system:notify_template:update', '通知模板 编辑', 'system'),
  ('system:openapi:read', 'OpenAPI 应用 查看', 'system'),
  ('system:openapi:update', 'OpenAPI 应用 维护', 'system'),
  ('system:param:read', '系统参数 查看', 'system'),
  ('system:param:update', '系统参数 维护', 'system'),
  ('system:payment_channel:read', '支付渠道 查看', 'system'),
  ('system:payment_channel:update', '支付渠道 配置', 'system'),
  ('system:problem:read', '问题类型 查看', 'system'),
  ('system:problem:update', '问题类型 编辑', 'system'),
  ('system:region:read', '地区库 查看', 'system'),
  ('system:tax:read', '税率与发票 查看', 'system'),
  ('system:tax:update', '税率与发票设置 编辑', 'system'),
  ('user:cuser:read', '用户 查看', 'user'),
  ('user:member:read', '会员 查看', 'user'),
  ('user:member:update', '会员 编辑', 'user'),
  ('user:risk:read', '风控名单 查看', 'user'),
  ('user:risk:update', '风控/黑名单 处置', 'user'),
  ('user:wallet:read', '钱包 查看', 'user'),
  ('user:wallet:update', '用户钱包 调账', 'user'),
  ('workorder:*', '工单 全部', 'workorder'),
  ('workorder:alarm:config', '告警代码/通知规则 配置', 'workorder'),
  ('workorder:alarm:update', '告警规则 维护', 'workorder'),
  ('workorder:inspection:update', '巡检计划 配置', 'workorder'),
  ('workorder:sla:update', 'SLA 配置', 'workorder'),
  ('workorder:wo:audit', '工单 审核', 'workorder'),
  ('workorder:wo:close', '工单 验收关单', 'workorder'),
  ('workorder:wo:create', '工单 开单', 'workorder'),
  ('workorder:wo:dispatch', '工单 派单/退回', 'workorder'),
  ('workorder:wo:handle', '工单 接单/处理/完成', 'workorder'),
  ('workorder:wo:process', '工单 处理', 'workorder'),
  ('workorder:wo:read', '工单 查看/看板', 'workorder'),
  ('workorder:wo:update', '工单 编辑', 'workorder')
ON DUPLICATE KEY UPDATE name = VALUES(name), module = VALUES(module);
