-- ============================================================
-- ShareHub · 菜单加两条叶子：用户管理 › 注销申请 / 开票申请
--
-- 【为什么加一条菜单要写迁移】
-- 菜单真源 V67 起在库里，所以菜单的维护入口本身也是一条菜单。
-- 这是「菜单真源迁进库」的代价，V81 的注释已经记过。
--
-- 【这两条是干什么的】
-- C 端一直在产生这两类待办（注销申请走冷静期、开票申请等受理），
-- 而运营端**此前没有任何入口** —— 不报错、不红、用户也不会投诉，
-- 因为他们不知道本该有。后端端点与权限码在上一个提交里已经落好
-- （user:logoff:read / :revoke、user:invoice:read / :handle）。
--
-- 【为什么是整表重灌而不是两条 INSERT】
-- 卡口 ops-web/lib/nav-seed.test.ts 拿本文件与 nav.ts **逐字段**比对，
-- 而 sort 是组内序号：往「用户主体」组中间插一条，后面所有叶子的 sort 都要跟着挪。
-- 两条 INSERT 做不到「相等」，只能做到「看起来差不多」，而差的那几行不会有东西报错。
--
-- **永远新开一个迁移，不要改 V81** —— 别人的库可能已经跑过它，
-- 改了 Flyway 会因校验和不符拒绝启动。
-- ============================================================
SET NAMES utf8mb4;

DELETE FROM iam_menu;

-- 本段由 lib/__gen_menu_seed.test.ts 从 ops-web/lib/nav.ts 生成，请勿手改。
-- 共 130 行（18 个 section + 112 个叶子）。
INSERT INTO iam_menu (menu_no, parent_no, name, name_en, name_ar, type, path, icon, group_name, sort, perm, phase, ready, module, modules, match_paths, pin_bottom, portal_for) VALUES
  ('M_my-biz', NULL, '我的经营', 'My Business', 'أعمالي', 'MENU', '/', 'LayoutDashboard', NULL, 1, NULL, 1, 0, 'dashboard', NULL, NULL, 0, '["AGENT"]'),
  ('M_my-biz__1', 'M_my-biz', '我的看板', 'My Dashboard', 'لوحتي', 'ITEM', '/', NULL, '经营概览', 1, 'dashboard:overview:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_my-biz__2', 'M_my-biz', '我的收益', 'My Earnings', 'أرباحي', 'ITEM', '/finance?tab=records', NULL, '经营概览', 2, 'finance:share_record:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_my-biz__3', 'M_my-biz', '我的结算', 'My Settlements', 'تسوياتي', 'ITEM', '/finance?tab=settlements', NULL, '经营概览', 3, 'agent:settlement:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_my-biz__4', 'M_my-biz', '申请提现', 'Request Withdrawal', 'طلب سحب', 'ITEM', '/finance?tab=withdrawals', NULL, '经营概览', 4, 'finance:withdrawal:apply', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_my-asset', NULL, '我的资产', 'My Assets', 'أصولي', 'MENU', '/devices', 'Server', NULL, 2, NULL, 1, 0, 'device', NULL, NULL, 0, '["AGENT"]'),
  ('M_my-asset__1', 'M_my-asset', '我的设备', 'My Devices', 'أجهزتي', 'ITEM', '/devices', NULL, '设备与订单', 1, 'device:cabinet:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_my-asset__2', 'M_my-asset', '我的订单', 'My Orders', 'طلباتي', 'ITEM', '/orders', NULL, '设备与订单', 2, 'order:order:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_my-service', NULL, '我的服务', 'My Service', 'خدماتي', 'MENU', '/work-orders', 'Wrench', NULL, 3, NULL, 1, 0, 'workorder', NULL, NULL, 0, '["AGENT"]'),
  ('M_my-service__1', 'M_my-service', '设备报修', 'Report Fault', 'الإبلاغ عن عطل', 'ITEM', '/work-orders?view=list', NULL, '报修与跟进', 1, 'workorder:wo:create', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_dashboard', NULL, '经营看板', 'Dashboard', 'لوحة المعلومات', 'MENU', '/', 'LayoutDashboard', NULL, 4, 'dashboard:overview:read', 1, 0, 'dashboard', NULL, NULL, 0, NULL),
  ('M_operation', NULL, '运营管理', 'Operations', 'إدارة العمليات', 'MENU', '/operation/overview', 'Store', NULL, 5, NULL, 1, 0, 'location', '["location","pricing","finance","system","marketing"]', '["/operation","/locations"]', 0, NULL),
  ('M_operation__1', 'M_operation', '站点概览', 'Site Overview', 'نظرة عامة على المواقع', 'ITEM', '/operation/overview', NULL, '场站管理', 1, 'location:overview:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__2', 'M_operation', '站点管理', 'Sites', 'المواقع', 'ITEM', '/operation/sites', NULL, '场站管理', 2, 'location:poi:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__3', 'M_operation', '点位管理', 'Points', 'النقاط', 'ITEM', '/locations?tab=points', NULL, '场站管理', 3, 'location:poi:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__4', 'M_operation', '站点坪效', 'Site Yield', 'أداء المواقع', 'ITEM', '/locations?tab=analysis', NULL, '场站管理', 4, 'location:analysis:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__5', 'M_operation', '收费方案', 'Fee Plans', 'خطط الرسوم', 'ITEM', '/operation/fee-plans', NULL, '计费与调价', 5, 'pricing:plan:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__6', 'M_operation', '预约调价', 'Scheduled Price Changes', 'تعديلات الأسعار المجدولة', 'ITEM', '/operation/fee-adjustments', NULL, '计费与调价', 6, 'pricing:adjustment:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__7', 'M_operation', '应用版本', 'App Versions', 'إصدارات التطبيق', 'ITEM', '/operation/app-versions', NULL, '基础管理', 7, 'system:app_version:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__8', 'M_operation', '银行管理', 'Banks', 'البنوك', 'ITEM', '/operation/banks', NULL, '基础管理', 8, 'system:bank:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__9', 'M_operation', '品牌管理', 'Brands', 'العلامات التجارية', 'ITEM', '/operation/brands', NULL, '基础管理', 9, 'system:brand:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__10', 'M_operation', '问题管理', 'Issue Types', 'أنواع المشكلات', 'ITEM', '/operation/problems', NULL, '基础管理', 10, 'system:problem:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__11', 'M_operation', '公告管理', 'Announcements', 'الإعلانات العامة', 'ITEM', '/operation/notices', NULL, '基础管理', 11, 'marketing:notice:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__12', 'M_operation', '站点分成', 'Site Revenue Share', 'حصص إيرادات المواقع', 'ITEM', '/operation/site-sharing', NULL, '分成', 12, 'finance:share_rule:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_operation__13', 'M_operation', '分成方分成', 'Payee Revenue Share', 'حصص المستفيدين', 'ITEM', '/operation/payee-sharing', NULL, '分成', 13, 'finance:share_rule:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_device', NULL, '设备管理', 'Devices', 'الأجهزة', 'MENU', '/devices', 'Server', NULL, 6, NULL, 1, 0, 'device', NULL, NULL, 0, NULL),
  ('M_device__1', 'M_device', '设备台账', 'Cabinets', 'الخزائن', 'ITEM', '/devices', NULL, '资产台账', 1, 'device:cabinet:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_device__2', 'M_device', '充电宝管理', 'Power Banks', 'بنوك الطاقة', 'ITEM', '/devices?tab=powerbanks', NULL, '资产台账', 2, 'device:powerbank:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_device__3', 'M_device', '实时监控', 'Monitoring', 'المراقبة', 'ITEM', '/devices?tab=monitor', NULL, '在线运行', 3, 'device:cabinet:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_device__4', 'M_device', '远程控制·指令记录', 'Remote & Commands', 'التحكم والأوامر', 'ITEM', '/devices?tab=commands', NULL, '在线运行', 4, 'device:command:send', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_device__5', 'M_device', '设备日志', 'Device Logs', 'سجلات الجهاز', 'ITEM', '/devices?tab=logs', NULL, '在线运行', 5, 'device:cabinet:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_device__6', 'M_device', '库存调拨', 'Inventory', 'المخزون', 'ITEM', '/devices?tab=inventory', NULL, '资产流转', 6, 'device:inventory:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_device__7', 'M_device', '固件 OTA', 'Firmware OTA', 'تحديث البرمجيات', 'ITEM', '/devices?tab=ota', NULL, '资产流转', 7, 'device:ota:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_device__8', 'M_device', '设备编码', 'Device Codes', 'أكواد الأجهزة', 'ITEM', '/devices?tab=codes', NULL, '资产流转', 8, 'device:cabinet:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_alarm', NULL, '告警管理', 'Alarms', 'الإنذارات', 'MENU', '/alarms', 'BellRing', NULL, 7, NULL, 1, 0, 'workorder', NULL, NULL, 0, NULL),
  ('M_alarm__1', 'M_alarm', '告警记录', 'Alarm Records', 'سجلات الإنذار', 'ITEM', '/alarms', NULL, '告警处置', 1, 'workorder:wo:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_alarm__2', 'M_alarm', '告警通知', 'Alarm Notices', 'إشعارات الإنذار', 'ITEM', '/alarms?tab=notices', NULL, '告警处置', 2, 'workorder:wo:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_alarm__3', 'M_alarm', '告警代码', 'Alarm Codes', 'أكواد الإنذار', 'ITEM', '/alarms?tab=codes', NULL, '规则配置', 3, 'workorder:wo:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_alarm__4', 'M_alarm', '通知规则', 'Notify Rules', 'قواعد الإشعار', 'ITEM', '/alarms?tab=rules', NULL, '规则配置', 4, 'workorder:wo:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_workorder', NULL, '工单管理', 'Work Orders', 'أوامر العمل', 'MENU', '/work-orders', 'Wrench', NULL, 8, NULL, 1, 0, 'workorder', NULL, NULL, 0, NULL),
  ('M_workorder__1', 'M_workorder', '工单列表', 'List', 'القائمة', 'ITEM', '/work-orders?view=list', NULL, NULL, 1, 'workorder:wo:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_workorder__2', 'M_workorder', '工单看板', 'Board', 'اللوحة', 'ITEM', '/work-orders?view=board', NULL, NULL, 2, 'workorder:wo:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_workorder__3', 'M_workorder', 'SLA 管理', 'SLA', 'اتفاقية الخدمة', 'ITEM', '/work-orders?view=sla', NULL, NULL, 3, 'workorder:wo:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_workorder__4', 'M_workorder', '巡检计划', 'Inspections', 'خطط التفتيش', 'ITEM', '/work-orders?view=inspection', NULL, NULL, 4, 'workorder:wo:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_venue', NULL, '场地方与拓展', 'Venues & BD', 'الأماكن وتطوير الأعمال', 'MENU', '/venues?tab=venues', 'Building2', NULL, 9, NULL, 1, 0, 'location', NULL, '["/venues"]', 0, NULL),
  ('M_venue__1', 'M_venue', '场地方', 'Venues', 'الأماكن', 'ITEM', '/venues?tab=venues', NULL, '机构档案', 1, 'location:venue:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_venue__2', 'M_venue', '进场合同', 'Contracts', 'العقود', 'ITEM', '/venues?tab=contracts', NULL, '机构档案', 2, 'location:contract:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_venue__3', 'M_venue', 'BD 拓展 CRM', 'BD CRM', 'إدارة العملاء', 'ITEM', '/venues?tab=crm', NULL, '拓展', 3, 'location:lead:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_venue__4', 'M_venue', '门店 Onboarding', 'Store Onboarding', 'تسجيل المتاجر', 'ITEM', '/venues?tab=onboarding', NULL, '拓展', 4, 'location:venue:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_venue__5', 'M_venue', '门店生命周期', 'Store Lifecycle', 'دورة حياة المتجر', 'ITEM', '/venues?tab=lifecycle', NULL, '拓展', 5, 'location:venue:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_agent', NULL, '代理商管理', 'Agents', 'الوكلاء', 'MENU', '/agents', 'Handshake', NULL, 10, NULL, 1, 0, 'agent', NULL, NULL, 0, NULL),
  ('M_agent__1', 'M_agent', '入驻审核', 'Onboarding Review', 'مراجعة الانضمام', 'ITEM', '/agents?tab=applies', NULL, '机构档案', 1, 'agent:apply:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_agent__2', 'M_agent', '代理商档案', 'Agent Profiles', 'ملفات الوكلاء', 'ITEM', '/agents', NULL, '机构档案', 2, 'agent:agent:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_agent__3', 'M_agent', '代理账号管理', 'Agent Accounts', 'حسابات الوكلاء', 'ITEM', '/agents?tab=accounts', NULL, '机构档案', 3, 'agent:agent:update', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_agent__4', 'M_agent', '设备/点位划拨', 'Allocation', 'التخصيص', 'ITEM', '/agents?tab=assign', NULL, '机构档案', 4, 'agent:scope:assign', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_agent__5', 'M_agent', '分润配置', 'Commission Setup', 'إعداد العمولة', 'ITEM', '/agents?tab=commission', NULL, '机构收益', 5, 'agent:share:config', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_agent__6', 'M_agent', '代理收益结算', 'Agent Settlement', 'تسوية الوكلاء', 'ITEM', '/finance?tab=settlements', NULL, '机构收益', 6, 'agent:settlement:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_agent__7', 'M_agent', '代理绩效', 'Agent Performance', 'أداء الوكلاء', 'ITEM', '/agents?tab=performance', NULL, '机构经营', 7, 'agent:performance:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_order', NULL, '订单管理', 'Orders', 'الطلبات', 'MENU', '/orders', 'ReceiptText', NULL, 11, NULL, 1, 0, 'order', NULL, NULL, 0, NULL),
  ('M_order__1', 'M_order', '订单列表', 'Orders', 'الطلبات', 'ITEM', '/orders', NULL, '交易流水', 1, 'order:order:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_order__2', 'M_order', '预约订单', 'Reservations', 'الحجوزات', 'ITEM', '/orders?tab=reservations', NULL, '交易流水', 2, 'order:order:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_order__3', 'M_order', '异常订单', 'Exceptions', 'الطلبات الشاذة', 'ITEM', '/orders?tab=exceptions', NULL, '售后处置', 3, 'order:exception:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_order__4', 'M_order', '投诉订单', 'Complaints', 'الشكاوى', 'ITEM', '/orders?tab=complaints', NULL, '售后处置', 4, 'order:exception:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_order__5', 'M_order', '退款记录', 'Refunds', 'المبالغ المستردة', 'ITEM', '/orders?tab=refunds', NULL, '售后处置', 5, 'order:refund:audit', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_order__6', 'M_order', '押金与欠费', 'Deposits & Arrears', 'الودائع والمتأخرات', 'ITEM', '/orders?tab=deposit', NULL, '特殊单据', 6, 'order:order:read', 1, 1, NULL, NULL, NULL, 0, NULL),
  ('M_order__7', 'M_order', '免费订单', 'Free Orders', 'طلبات مجانية', 'ITEM', '/orders?tab=free', NULL, '特殊单据', 7, 'order:order:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance', NULL, '财务管理', 'Finance', 'المالية', 'MENU', '/finance', 'Wallet', NULL, 12, NULL, 1, 0, 'finance', NULL, NULL, 0, NULL),
  ('M_finance__1', 'M_finance', '分润规则', 'Share Rules', 'قواعد التقسيم', 'ITEM', '/finance?tab=rules', NULL, '分润与结算', 1, 'finance:share_rule:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__2', 'M_finance', '分润明细', 'Share Records', 'سجلات التقسيم', 'ITEM', '/finance?tab=records', NULL, '分润与结算', 2, 'finance:share_record:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__3', 'M_finance', '分润统计', 'Sharing Summary', 'ملخص التقسيم', 'ITEM', '/finance?tab=summary', NULL, '分润与结算', 3, 'finance:share_record:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__4', 'M_finance', '结算单', 'Settlements', 'التسويات', 'ITEM', '/finance?tab=settlements', NULL, '分润与结算', 4, 'finance:settlement:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__5', 'M_finance', '账务分录', 'Ledger', 'القيود المحاسبية', 'ITEM', '/finance?tab=ledger', NULL, '平台账', 5, 'finance:ledger:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__6', 'M_finance', '对账', 'Reconcile', 'المطابقة', 'ITEM', '/finance?tab=reconcile', NULL, '平台账', 6, 'finance:recon:read', 1, 1, NULL, NULL, NULL, 0, NULL),
  ('M_finance__7', 'M_finance', '发票', 'Invoices', 'الفواتير', 'ITEM', '/finance?tab=invoices', NULL, '平台账', 7, 'finance:invoice:read', 2, 1, NULL, NULL, NULL, 0, NULL),
  ('M_finance__8', 'M_finance', '代理分润配置', 'Agent Commission', 'عمولة الوكلاء', 'ITEM', '/agents?tab=commission', NULL, '伙伴账', 8, 'agent:share:config', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__9', 'M_finance', '提现审核', 'Withdrawals', 'طلبات السحب', 'ITEM', '/finance?tab=withdrawals', NULL, '伙伴账', 9, 'finance:withdrawal:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__10', 'M_finance', '收款账户', 'Payout Accounts', 'حسابات التحويل', 'ITEM', '/finance?tab=payout-accounts', NULL, '伙伴账', 10, 'finance:payout_account:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__11', 'M_finance', '用户钱包', 'User Wallets', 'محافظ المستخدمين', 'ITEM', '/users?tab=wallets', NULL, '用户账', 11, 'user:wallet:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_finance__12', 'M_finance', '充值订单', 'Top-up Orders', 'طلبات الشحن', 'ITEM', '/finance?tab=recharges', NULL, '用户账', 12, 'user:wallet:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_user', NULL, '用户管理', 'Users', 'المستخدمون', 'MENU', '/users', 'UserCircle', NULL, 13, NULL, 1, 0, 'user', NULL, NULL, 0, NULL),
  ('M_user__1', 'M_user', '用户列表', 'Users', 'المستخدمون', 'ITEM', '/users', NULL, '用户主体', 1, 'user:cuser:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_user__2', 'M_user', '注销申请', 'Account Deletions', 'طلبات حذف الحساب', 'ITEM', '/users?tab=logoffs', NULL, '用户主体', 2, 'user:logoff:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_user__3', 'M_user', '风控用户', 'Risk Users', 'المستخدمون المحفوفون بالمخاطر', 'ITEM', '/users?tab=risk', NULL, '风险治理', 3, 'user:risk:read', 1, 1, NULL, NULL, NULL, 0, NULL),
  ('M_user__4', 'M_user', '黑名单', 'Blacklist', 'القائمة السوداء', 'ITEM', '/users?tab=blacklist', NULL, '风险治理', 4, 'user:risk:update', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_user__5', 'M_user', '免费用户白名单', 'Free Users', 'المستخدمون المجانيون', 'ITEM', '/users?tab=whitelist', NULL, '风险治理', 5, 'user:risk:update', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_user__6', 'M_user', '会员/次卡', 'Members', 'الأعضاء', 'ITEM', '/users?tab=members', NULL, '用户资产', 6, 'user:member:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_user__7', 'M_user', '钱包', 'Wallets', 'المحافظ', 'ITEM', '/users?tab=wallets', NULL, '用户资产', 7, 'user:wallet:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_user__8', 'M_user', '充值套餐', 'Top-up Packages', 'باقات الشحن', 'ITEM', '/users?tab=recharge', NULL, '用户资产', 8, 'user:wallet:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_user__9', 'M_user', '开票申请', 'Invoice Requests', 'طلبات الفواتير', 'ITEM', '/users?tab=invoices', NULL, '用户资产', 9, 'user:invoice:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_marketing', NULL, '营销管理', 'Marketing', 'التسويق', 'MENU', '/marketing', 'Ticket', NULL, 14, NULL, 1, 0, 'marketing', NULL, NULL, 0, NULL),
  ('M_marketing__1', 'M_marketing', '优惠券', 'Coupons', 'القسائم', 'ITEM', '/marketing', NULL, '促销玩法', 1, 'marketing:coupon:read', 2, 1, NULL, NULL, NULL, 0, NULL),
  ('M_marketing__2', 'M_marketing', '活动', 'Campaigns', 'الحملات', 'ITEM', '/marketing?tab=campaigns', NULL, '促销玩法', 2, 'marketing:campaign:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_marketing__3', 'M_marketing', '推送触达', 'Push', 'الإشعارات', 'ITEM', '/marketing?tab=push', NULL, '促销玩法', 3, 'marketing:push:send', 3, 1, NULL, NULL, NULL, 0, NULL),
  ('M_marketing__4', 'M_marketing', '邀请裂变', 'Referrals', 'الإحالات', 'ITEM', '/marketing?tab=referral', NULL, '促销玩法', 4, 'marketing:campaign:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_marketing__5', 'M_marketing', '广告位管理', 'Ad Slots', 'مساحات الإعلان', 'ITEM', '/marketing?tab=ad-slots', NULL, '广告经营', 5, 'marketing:ad:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_marketing__6', 'M_marketing', '广告活动', 'Ad Campaigns', 'حملات الإعلان', 'ITEM', '/marketing?tab=ad-campaigns', NULL, '广告经营', 6, 'marketing:ad:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_marketing__7', 'M_marketing', '投放与曝光', 'Ad Delivery', 'عرض الإعلانات', 'ITEM', '/marketing?tab=ad-delivery', NULL, '广告经营', 7, 'marketing:ad:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_cs', NULL, '客服管理', 'Support', 'الدعم', 'MENU', '/cs', 'Headset', NULL, 15, NULL, 1, 0, 'cs', NULL, NULL, 0, NULL),
  ('M_cs__1', 'M_cs', '报障受理', 'Tickets', 'تذاكر الأعطال', 'ITEM', '/cs', NULL, NULL, 1, 'cs:ticket:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_cs__2', 'M_cs', '客服会话', 'Sessions', 'المحادثات', 'ITEM', '/cs?tab=sessions', NULL, NULL, 2, 'cs:session:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_cs__3', 'M_cs', '退款/补偿', 'Refunds', 'المبالغ المستردة', 'ITEM', '/orders', NULL, NULL, 3, 'order:refund:apply', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_cs__4', 'M_cs', '黑名单处理', 'Blacklist', 'القائمة السوداء', 'ITEM', '/users', NULL, NULL, 4, 'user:risk:update', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_report', NULL, '数据报表', 'Reports', 'التقارير', 'MENU', '/reports', 'ChartColumn', NULL, 16, NULL, 1, 0, 'report', NULL, NULL, 0, NULL),
  ('M_report__1', 'M_report', '设备运营分析', 'Device Analytics', 'تحليلات الأجهزة', 'ITEM', '/reports?tab=device', NULL, NULL, 1, 'report:device:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_report__2', 'M_report', '点位坪效', 'Point Yield', 'أداء النقاط', 'ITEM', '/reports?tab=location', NULL, NULL, 2, 'report:location:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_report__3', 'M_report', '财务报表', 'Financials', 'التقارير المالية', 'ITEM', '/reports?tab=finance', NULL, NULL, 3, 'report:finance:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_report__4', 'M_report', '实时大屏', 'Live Wall', 'الشاشة المباشرة', 'ITEM', '/reports?tab=screen', NULL, NULL, 4, 'report:screen:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_report__5', 'M_report', '自定义报表', 'Custom', 'تقارير مخصصة', 'ITEM', '/reports?tab=custom', NULL, NULL, 5, 'report:custom:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_report__6', 'M_report', '消费者分析', 'Consumer Analytics', 'تحليلات المستهلك', 'ITEM', '/reports?tab=consumer', NULL, NULL, 6, 'report:consumer:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_org', NULL, '员工与权限', 'Staff & Roles', 'الموظفون والأدوار', 'MENU', '/employees', 'Users', NULL, 17, NULL, 1, 0, 'org', NULL, NULL, 0, NULL),
  ('M_org__1', 'M_org', '员工', 'Employees', 'الموظفون', 'ITEM', '/employees?tab=employees', NULL, '人与组织', 1, 'org:employee:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_org__2', 'M_org', '组织架构', 'Org Chart', 'الهيكل التنظيمي', 'ITEM', '/employees?tab=org', NULL, '人与组织', 2, 'org:employee:read', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_org__3', 'M_org', '角色权限', 'Roles', 'الأدوار', 'ITEM', '/employees?tab=roles', NULL, '授权', 3, 'org:role:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_org__4', 'M_org', '菜单管理', 'Menu Settings', 'إعدادات القائمة', 'ITEM', '/employees?tab=menus', NULL, '授权', 4, 'org:role:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_org__5', 'M_org', '操作审计', 'Audit Log', 'سجل التدقيق', 'ITEM', '/employees?tab=audit', NULL, '留痕与考核', 5, 'org:audit:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_org__6', 'M_org', '绩效报表', 'Performance', 'الأداء', 'ITEM', '/employees?tab=performance', NULL, '留痕与考核', 6, 'org:employee:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system', NULL, '系统设置', 'Settings', 'الإعدادات', 'MENU', '/system?tab=vendors', 'Settings', NULL, 18, NULL, 1, 0, 'system', NULL, '["/system"]', 1, NULL),
  ('M_system__1', 'M_system', '供应商接入', 'Vendors', 'الموردون', 'ITEM', '/system?tab=vendors', NULL, '接入与支付', 1, 'device:vendor:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__2', 'M_system', '支付渠道', 'Payment Channels', 'قنوات الدفع', 'ITEM', '/system?tab=payment', NULL, '接入与支付', 2, 'system:payment_channel:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__3', 'M_system', '通知模板', 'Templates', 'قوالب الإشعارات', 'ITEM', '/system?tab=notify', NULL, '消息触达', 3, 'system:notify_template:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__4', 'M_system', '发送记录', 'Delivery Log', 'سجل الإرسال', 'ITEM', '/system?tab=notify-log', NULL, '消息触达', 4, 'system:notify_log:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__5', 'M_system', '触达拉黑', 'Notify Blacklist', 'قائمة حظر الإشعارات', 'ITEM', '/system?tab=notify-blacklist', NULL, '消息触达', 5, 'system:notify_blacklist:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__6', 'M_system', '业务规则', 'Business Rules', 'قواعد العمل', 'ITEM', '/system?tab=rules', NULL, '业务规则', 6, 'system:biz_rule:update', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__7', 'M_system', '登录设置', 'Sign-in Settings', 'إعدادات الدخول', 'ITEM', '/system?tab=login', NULL, '业务规则', 7, 'system:login_setting:update', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__8', 'M_system', '参数字典', 'Dictionaries', 'القواميس', 'ITEM', '/system?tab=dict', NULL, '基础字典', 8, 'system:dict:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__9', 'M_system', '地区库', 'Regions', 'المناطق', 'ITEM', '/system?tab=region', NULL, '基础字典', 9, 'system:dict:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__10', 'M_system', '系统参数', 'Parameters', 'المعاملات', 'ITEM', '/system?tab=params', NULL, '基础字典', 10, 'system:param:read', 1, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__11', 'M_system', '税率与发票', 'Tax & Invoice', 'الضريبة والفواتير', 'ITEM', '/system?tab=tax', NULL, '开放与市场', 11, 'system:tax:update', 2, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__12', 'M_system', '多国家市场', 'Markets', 'الأسواق الدولية', 'ITEM', '/system?tab=markets', NULL, '开放与市场', 12, 'system:market:read', 3, 0, NULL, NULL, NULL, 0, NULL),
  ('M_system__13', 'M_system', 'OpenAPI 应用', 'OpenAPI Apps', 'تطبيقات OpenAPI', 'ITEM', '/system?tab=openapi', NULL, '开放与市场', 13, 'system:openapi:read', 3, 0, NULL, NULL, NULL, 0, NULL);